frontend/.eslintrc.cjs
frontend/package-lock.json
frontend/package.json

eslint 에러 해결 close #99
- eslint 에러 발생 `Unable to resolve path to module '/vite.svg'.eslint [import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.29.0/docs/rules/no-unresolved.md)` 에러
- `Do not import modules using an absolute patheslint[import/no-absolute-path](https://github.com/import-js/eslint-plugin-import/blob/v2.29.0/docs/rules/no-absolute-path.md)` 에러
eslint-import-resolver-alias 설치 및 .eslintrc.cjs 수정으로 해결

Feature(#99): eslint-import-resolver-alias 라이브러리 설치

---

frontend/package-lock.json
frontend/package.json
frontend/tsconfig.json
frontend/vite.config.ts
package-lock.json

vite-plugin-svgr 패키지 설치 close #101 
- svgr 초기 설정
- tsconfig.json내 compilerOptions에 "types": ["vite-plugin-svgr/client"], 옵션 추가
vite-plugin-svgr을 설치하고, svg 파일을 import 하여 적용해보려는 시도 중, svg 파일이 정상적으로 불러와지지 않고 에러가 나는 상황이 발생했습니다.
처음에는 경로 지정 문제로 판단해서 경로를 절대 경로로 변경하는 등의 시도를 해 보았지만, 경로 수정으로는 문제를 해결할 수 없었습니다.
`해결`
vite-plugin-svgr이 v4.0.0으로 업데이트 되면서 svg 파일을 import 하는 방법이 변경되어서 생긴 문제였습니다. 불러오기를 다음과 같이 변경하여 문제를 해결했습니다.
```jsx
// import Logo from "./logo.svg"; (에러)
import Logo from "./logo.svg?react";
```
import 해오는 경로 뒤에 `?react`가 붙을 경우 typescript에서 ts(2307)에러를 발생시켰습니다.
`해결`
tsconfig.json에 compilerOptions에  **"types": ["vite-plugin-svgr/client"]**를 추가하여 해결했습니다. 이 옵션은  패키지의 타입 정의를 프로젝트에 추가한다는 것을 나타냅니다.
```json
// tsconfig.json
{
"compilerOptions": {
...
**"types": ["vite-plugin-svgr/client"],**
...
} …
```

Feature(#101): svgr 초기 세팅

---

frontend/src/App.tsx
frontend/src/components/Header/components/LeftSection.tsx
frontend/src/components/Header/components/ProfileModal.tsx
frontend/src/pages/MyPage/MyPage.tsx

Header 컴포넌트 navigate 추가 #62 
- 로고 클릭 시에 Main으로 이동하도록 onClick 이벤트 추가
- 마이페이지로 이동 확인을 위해 마이페이지 파일 추가
- 사용자 정보 모달에서 '마이페이지' 버튼 클릭 시에 onClick 이벤트 추가
~~없음~~
https://github.com/boostcampwm2023/web13_Boarlog/assets/79556112/3cabbe3d-b5ee-405a-9fa2-313c80c34838

Feature(#62): Header 컴포넌트 navigate 추가

---

frontend/src/pages/Test/components/StickyNoteEditPanel.tsx
frontend/src/pages/Test/components/stateStickyNoteInstance.ts

캔버스 클릭 후 메모 클릭시 글꼴 초기화 되는 문제 해결 close #142 
- 원인: StickyNoteEditPanel 컴포넌트가 랜더링되어 있지 않다가 StickyNoteEditPanel 컴포넌트 랜더링시 useState의 초기 값을 m, left로 재 설정하기 때문에 메모지의 상태가 리셋이 되는 문제가 발생했습니다.
```
// StickyNoteEditPanel.tsx 중
const [fontSize, setFontSize] = useState<FontSize>("m");
const [formatAlign, setFormatAlign] = useState<FormatAlign>("left");
```
- 해결: useState의 초기 값을 선택된 메모의 데이터(폰트 사이즈, 정렬)를 getClickedMemoData함수를 통해 가져와 맵핑
https://github.com/boostcampwm2023/web13_Boarlog/assets/54176384/c847e3ca-bc79-4c0e-9507-24de0760aa5b
https://github.com/boostcampwm2023/web13_Boarlog/assets/54176384/fc8c9e7d-9b2d-48af-aee6-5d62d88560d4

Fix(#142): 캔버스 클릭 후 메모 클릭시 글꼴 초기화 되는 문제 해결

---

mediaServer/package-lock.json
mediaServer/package.json
mediaServer/src/RelayServer.ts
mediaServer/src/main.ts
mediaServer/test/presenter/index.html
mediaServer/test/student/index.html

close #149 `배포 환경에서 사용자들끼리 webRTC를 연결하고 MediaStream을 주고 받는다.`
로컬에서는 잘 되는데 배포환경에서 접속했을 때 webRTC 연결이 제대로 되지 않는 문제를 해결했습니다.
서로 connection 연결할 때 turn 서버를 설정해줘서 연결이 잘 되도록 수정했습니다.
배포 서버에서 turn 서버 구축을 해주어서 코드 상 변화는 크게 없습니다.
test용 html 파일에서 `pc_config` 안에 turn 서버 url이나 username, password를 적어줘야 하는데 html 파일 안에 값을 바로 적으면 값들이 노출되기 때문에 다른 방법을 찾아보았습니다. `RelayServer.ts`에서는 환경변수를 활용해서 `process.env.변수이름`으로 호출하는 방법을 선택했는데 html 파일 내에서는 환경변수를 사용할 수 없어서 고민이 되었습니다. 해당 파일은 테스트용 html 파일이고 실제 프론트엔드와 합치게 되면 React 내에서 환경변수를 써서 동적으로 바꿔주는 게 가능하기 때문에, 테스트용 html은 해당 내용을 비워두기로 결정했습니다. 배포환경에서 테스트할 시에 html 내의 값들을 채워주고 테스트해주면 됩니다.

Fix(#149) 배포환경에서 MediaStream 참여자가 못 받는 문제 수정

---

frontend/src/pages/Test/components/Toolbar.tsx

화이트보드(지우개, 메모지) 관련 버그 수정
fix: 지우개 툴 선택 후 선택툴 클릭시 요소 삭제 오류 해결 close #177
fix: 메모지 내에 입력한 개행이 사라지는 버그 close #178
- 원인: 지우개의 selection:created 이벤트가 등록된 상태로 선택 툴에서 같은 이벤트가 발생해 그래픽 요소 삭제
- 해결: 툴이 바뀔 때마다 이벤트를 지워주는 코드가 있는데 selection:created도 지우도록 했습니다.
- 원인: 메모지에 공백을 입력시 텍스트를 디폴트 값으로 바꿔주게 구현이 되어있습니다.
개행만 하고 다른 텍스트를 입력하지 않았을 때를 체크하기 위해 모든 개행문자를 제거하고 글자 수를 체크합니다.
이 개행문자가 제거된 텍스트가 편집후 메모지의 텍스트 내용으로 갱신되기 때문에 문제가 발생했습니다.
- 해결: 개행만하고 다른 문자를 입력하지 않는가를 체크하기 위해 개행을 제거하는 동작을 조건문 안에서만 실행되게 수정했습니다.
- 추가 사항: 개행 뿐만 아니라 띄어쓰기로만 이뤄진 텍스트인가도 체크하도록 정규표현식을 수정했습니다.
- 삭제 버그 해결
https://github.com/boostcampwm2023/web13_Boarlog/assets/54176384/ad232131-82f8-4bbc-a4de-3bb24ae4ebe9
- 개행 제거 버그 해결
https://github.com/boostcampwm2023/web13_Boarlog/assets/54176384/cbb396da-54bd-4717-a371-69cda4c7fc73

Fix(#177, #178): 화이트보드(지우개, 메모지) 관련 버그 수정

---

frontend/src/components/Header/components/HeaderInstructorControls.tsx
frontend/src/components/Header/components/HeaderParticipantControls.tsx

close #183 `강의 참여 시 발표자의 화면 로딩 시간이 길어지거나 아예 보이지 않는 이슈`
https://github.com/boostcampwm2023/web13_Boarlog/assets/86391351/d36cf45d-428f-4bf1-83b5-cc2f19489940
로컬에서 미디어 서버를 실행시켜 확인한 결과입니다.
발표자가 화이트보드를 건드리지 않아도 참여자 페이지에서 바로 화면이 보입니다.
노션 개발일지에 아래 내용을 정리했습니다.
https://weak-sugar-603.notion.site/eaa2870a3d194b06a2773605e63db3a5
**1) 화이트보드 화면이 언제 참여자 페이지에 렌더링 되는 건지 확인하기**
(로컬에 미디어 서버를 띄우고 테스트해봤습니다.)
https://github.com/boostcampwm2023/web13_Boarlog/assets/86391351/6578f06d-a1a9-4b67-a683-e0a59cb8ac8e
video의 메타데이터가 로드되었을 때 발생하는 `loadedmetadata` 와 함께 화면에 영상이 재생되는 것을 확인했습니다. 
**2) `loadedmetadata` 가 왜 늦게 발생하는가?**
여러가지 시도 끝에 알게 된 것은 강의자 페이지에서 **강의자가 캔버스에 아무런 동작(펜 그리기, 이동, 줌인 등)을 하지 않으면** 상대방에게 `loadedmetadata` 는 일어나지 않는다는 것입니다.
https://w3c.github.io/mediacapture-fromelement/#methods-0
이는 …

Fix(#183) 강의 참여시 곧바로 발표자의 화이트보드가 보이도록 개선

---

frontend/src/assets/svgs/sendMessage.svg
frontend/src/components/LogContainer/LogContainer.tsx
frontend/src/components/QuestionPromptLogContainer/QuestionPromptLogContainer.tsx
frontend/src/global.css
frontend/src/pages/Participant/Participant.tsx

채팅 사이드바 UI 구현 close #42
- 채팅 사이드바 UI 작업
- 채팅 공백시 버튼 비활성화 기능 구현
https://github.com/boostcampwm2023/web13_Boarlog/assets/54176384/1a4b337a-fd74-45b4-a0ec-f248597c08dc

Feature(#42): 강의 참여 페이지 채팅 사이드바를 사용자가 확인할 수 있다 (UI 작업) 

---

frontend/src/components/Header/components/HeaderInstructorControls.tsx
frontend/src/components/Header/components/HeaderParticipantControls.tsx
frontend/src/components/LogContainer/LogContainer.tsx

http://localhost:5173/Instructor?roomid=123456와 같이 주소창에 roomid를 넣어서 사용할 수있습니다.
같은 roomid를 가진 강의자의 발표만 참여자가 확인할 수 있습니다.
여기에 작성하세요
여기에 작성하세요

Feature(#69) 참여자 페이지 강의 시간 확인, 강의 코드에 맞춰서 강의실 생성/입장 구현

---

mediaServer/package-lock.json
mediaServer/package.json
mediaServer/src/config/ncp.config.ts
mediaServer/src/models/FfmpegCommand.ts
mediaServer/src/utils/ncp-storage.ts

close #59 `추출한 발표자의 미디어 파일을 NCP Object Storage에 저장한다.`
close #161 `강의가 종료되면 미디어서버에서 API 서버로 강의 정보와 함께 강의 완료 요청을 보낸다.`
기존에 로컬에 저장되던 mp4 파일을 읽어와서 NCP Object Storage에 저장했습니다. 저장한 뒤에는 저장 위치 url을 반환합니다. 해당 url을 DB에 업데이트 해주기 위해서 미디어서버에서 API 서버로 요청을 보냅니다. 
NCP에서 AWS S3에서 제공하는 Javascript용 SDK를 이용해 Object Storage를 사용하는 API를 제공하기에 이를 사용했습니다. 그 이유는 나중에 S3로 바꾸게 된다면 코드는 바꿀 필요 없이 환경변수 값만 바꿔주면 되기 때문에 확장성 부분에서 좋을 것 같다고 생각했기 때문입니다. 코드로 구현하는 과정에서도 S3를 사용해봤던 입장으로 더 익숙하기에 이를 사용했습니다.

Feature(#59, #161) 발표자 미디어 파일 Object Storage에 저장, DB에 강의 정보 업데이트

---

backend/src/lecture/interfaces/Subtitle.ts
backend/src/lecture/lecture-subtitle.schema.ts
backend/src/lecture/lecture.controller.ts
backend/src/lecture/lecture.module.ts
backend/src/lecture/lecture.service.ts

close #79 `클로바 API를 사용하여 음성을 글로 추출하고 자막으로 DB에 저장한다.`
CLOVA Speech 장문인식 API를 활용하여 미디어파일에서 음성을 텍스트로 추출했습니다. callback url로 API 결과가 리턴되면 이를 가공하여 DB에 저장합니다. DB에는 자막 문장별로 `발화시간`과 `문장내용` 형식으로 저장합니다.
자막을 나타내기 위한 `interface`를 다음과 같이 정의하였습니다.
```typescript
export interface Subtitle {
start: string;
text: string;
}
```
DB에는 다음과 같은 형태로 저장됩니다.
```JSON
[   
{"start": "20770", "text": "비슷한 사고가 4차례나 더 있었습니다. 앞서 시범 경기 기간에도 파월 공으로 인한 차량 파손 사고가 30여 차례나 발생했습니다."}, 
{"start": "32930", "text": "당초 이 야구장은 생활체육인을 위한 시설로 설계됐다가 전국 체전을 앞두고 공인규격 야구장으로 바뀌었습니다."}, 
]
```

Feature(#79): 클로바 API를 사용하여 음성을 글로 추출하고 자막으로 DB에 저장한다.

---

mediaServer/src/RelayServer.ts
mediaServer/src/models/RoomInfo.ts

강의실 입장 시 현 시점 화이트보드 데이터 전달 close #220 
기존에는 강의 중간에 참여 시, 발표자가 화이트보드를 수정하기 전까지 현 시점의 화이트보드를 받아볼 수 없었습니다.
따라서 미디어 서버에서 최신의 화이트보드 내용을 가지고 있다가, 새로운 참여자가 강의실에 입장하면 해당 데이터를 내려주는 방식으로 해결했습니다.
하지만, 현재 미디어 서버에서 가지고 있는 데이터가 너무 많아서, 추후 역할 분리를 해보려합니다.

Feature(#220): 강의실 입장 시 현 시점 화이트보드 데이터 전달

---

mediaServer/src/utils/ncp-storage.ts

이전에 mp4 형식으로 파일을 저장하도록 진행했는데, 미처 NCP에 저장될 파일 확장자를 수정하지 않아서 mp3로 변경했습니다.

Fix: NCP에 파일 업로드 시 mp3 확장자로 저장될 수 있도록 확장자 변경

---

frontend/src/pages/Test/components/CanvasSection.tsx

화이트보드-backspace로 그래픽 요소 지우기 구현 close #217

Refactor(#217): 화이트보드-backspace로 그래픽 요소 지우기 구현

---

frontend/global.d.ts
frontend/index.html
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/Header/components/HeaderParticipantControls.tsx
frontend/src/components/Toast/useToast.ts
frontend/src/main.tsx
frontend/src/modernizr.js
frontend/src/pages/Home/Home.tsx
frontend/src/pages/Home/components/JoinLectureBack.tsx
frontend/src/pages/Home/components/NewLectureBack.tsx
frontend/src/pages/Instructor/Instructor.tsx
frontend/tsconfig.json

- close #17 
- close #19 
- close #20 
- close #21
- close #205 
> 🔗[Modernizr download builder](https://modernizr.com/download?setclasses)
상단 페이지에서 `touch events`를 선택하여 `modernizr-custom.js`를 빌드하여 이를 `src` 폴더에 위치시킵니다. 전역으로 `Modernizr`를 사용하기 위하여 `index.html`에 `script` 태그를 이용하여 이를 불러옵니다.
```html
<script type="text/javascript" src="/src/modernizr.js"></script>
```
TypeScript 환경에서 작업하고 있기 때문에 이에 대한 type을 선언하였습니다. `types` 폴더 하위에 다양한 type들을 정의할 수 있도록 작업하려 하였으나 기존에 작업하였던 `"types": ["vite-plugin-svgr/client"],`과 `typesRoot` 설정이 겹쳐 `svg` 관련 코드가 정상적으로 동작하지 않을 것을 고려하여 `global`로 관리할 수 있도록 하였습니다.
`src` 하위에 `global.d.ts`를 정의하여 아래와 같이 `type`을 정의하였습니다.
```ts
declare global {
interface ModernizrStatic {
touchevents: boolean;
}
var Modernizr: ModernizrStatic;
}
export {};
```
이를 적용하기 위해 `tsconfig.json`에 …

Feature(#17, #19, #20, #21, #205): home 페이지 API 연동, modernizr 적용

---

backend/package-lock.json
backend/package.json
backend/src/auth/auth.controller.ts
backend/src/auth/auth.guard.ts
backend/src/auth/auth.service.ts
backend/src/auth/dto/auth.signin.dto.ts
backend/src/auth/dto/auth.signup.dto.ts
backend/src/auth/dto/userInfo.dto.ts
backend/src/auth/google.strategy.ts
backend/src/lecture/lecture.service.ts
backend/src/user/user.controller.ts
backend/src/user/user.module.ts
backend/src/user/user.schema.ts
backend/src/utils/GenerateUtils.ts

close #234 `Refactor: 로그인 방식 변경`
email과 password를 사용하여 회원가입 및 로그인을 진행하도록 수정했습니다. 
`user.schema.ts`에서 profile 필드를 제거하고 password 필드를 추가했습니다.
```Javascript
@Schema()
export class User {
@Prop({ required: true })
username: string;
@Prop({ required: true })
email: string;
@Prop()
password: string;
@Prop({ type: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Lecture' }] })
lecture_id: Lecture[];
}
```

Refactor: 로그인 방식 변경

---

frontend/src/components/Header/components/HeaderInstructorControls.tsx
frontend/src/components/Header/components/HeaderParticipantControls.tsx
frontend/src/components/Header/components/fabricCanvasUtil.ts
frontend/src/components/LogContainer/LogContainer.tsx
frontend/src/utils/calcNormalizedVolume.ts
frontend/src/utils/convertMsToTimeString.ts

강의자와 참여자 헤더의 코드를 간단하게 리팩토링 했습니다.
다음 PR 올릴 때 변경 사항이 많으면 코드리뷰 하시기 힘드실 것 같아서 리팩토링 한 내용만 먼저 PR 올립니다.
기능이 변한 것은 없어서 편하게 LGTM만 해주셔도 감사하겠습니다.
여기에 작성하세요
여기에 작성하세요

Refactor: 강의자/참여자 헤더 리팩토링

---

frontend/src/components/Header/components/HeaderCodeCopyButton.tsx
frontend/src/components/Toast/ToastContainer.tsx
frontend/src/components/Toast/useToast.ts
frontend/src/stores/stateToastList.ts

- close #249 
현재 프로젝트는 `dev`와 `main`으로 `local/dev/production`로 페이즈를 나누어 개발중에 있습니다. 강의 코드를 클립보드에 복사하여 링크를 공유하는 과정에서 `base-url`이 달라야 하기 때문에 이를 위해 `env`로 값을 달리하여 각 페이즈마다의 공유 링크를 가지도록 하였습니다.
추가적으로 state를 한 곳에 모아 관리하기 위해 `Toast`의 recoil state 관련 파일을 `src/stores`로 이동하여 구조 개선 작업을 시작하였습니다. (naming convention에 맞게 이름을 변경하였습니다.)
(뷰 변경사항 없음)

Refactor(#249): 링크 공유 개선, Toast state 분리

---

backend/src/lecture/lecture.controller.ts
backend/src/lecture/lecture.service.ts
backend/src/user/dto/userInfo.dto.ts
backend/src/user/user.controller.ts
backend/src/user/user.service.ts

강의 조회와 내 프로필 조회 API 분리
기존에 내 프로필 조회에서 username, email과 함께 수강한 강의 내역도 같이 응답해줬는데 이 두가지를 분리했으면 좋겠다는 프론트엔드 팀원분들의 의견에 따라 수정하였습니다.
강의 다시보기 정보 조회할 때 강의 id 값이 필요해 이 부분을 포함해서 응답하도록 수정했습니다.

Refactor: 강의 조회와 내 프로필 조회 API 분리

---

backend/src/auth/auth.controller.ts
backend/src/lecture/dto/create-lecture.dto.ts
backend/src/lecture/lecture.controller.ts

Refactor: 강의생성 API 로그인 된 사용자만 호출하도록 수정
강의생성하는 API를 기존에는 모든 사용자가 호출할 수 있었고 request body에 강의를 생성하려는 사용자 email이 담겨서 요청이 왔었는데 이 부분을 로그인한 사용자만 호출할 수 있도록 수정했습니다.
API 문서를 위한 swagger 설정들을 추가해줬습니다.
swagger 설정들을 추가하면서 코드가 깔끔하지 못해지는거 같아서 이 부분을 추후에 개선해봐야겠다.

Refactor: 강의생성 API 로그인 된 사용자만 호출하도록 수정

---

backend/src/auth/auth.controller.ts
backend/src/auth/auth.service.ts
backend/src/auth/dto/response-signin.dto.ts

로그인할 때 응답 형식 변경
기존의 응답 형식은 다음과 같습니다.
```JSON
{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuuCmOyVvOuCmOuCmOuCmCIsImVtYWlsIjoiaGkzMzNAZ21haWwuY29tIiwiaWF0IjoxNzAyMjg0NTA5LCJleHAiOjE3MDIyODgxMDl9.6qPN74WzJI8rGQP1Rp0zFO2hlmLCLQwHStMaWAo1vt4"
}
```
프론트엔드 팀원분의 요청에 따라 응답 형식을 다음과 같이 바꾸었습니다.
```JSON
{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuuCmOyVvOuCmOuCmOuCmCIsImVtYWlsIjoiaGkzMzNAZ21haWwuY29tIiwiaWF0IjoxNzAyMjg0NTA5LCJleHAiOjE3MDIyODgxMDl9.6qPN74WzJI8rGQP1Rp0zFO2hlmLCLQwHStMaWAo1vt4",
"email": "hihi@gmail.com",
"username": "나야나나나"
}
```

Refactor: 로그인할 때 응답 형식 변경

---

frontend/src/components/Header/components/HeaderInstructorControls.tsx
frontend/src/components/Header/components/HeaderParticipantControls.tsx
frontend/src/components/LogContainer/LogContainer.tsx
frontend/src/pages/Review/Review.tsx
frontend/src/pages/Review/components/ProgressBar.tsx

close #81 `AI 기반으로 생성한 강의 프롬프트 표시한다. 특정 시간대의 프롬프트를 표시할 수 있다.`
close #86 `강의 시간에 따라 음성을 출력한다.`
강의 프롬프트를 어디서 불러와야 하나 고민했습니다.
현재는 강의 프롬프트, 화이트보드 데이터, 강의 음성이 모두 한번의 API요청으로 불러오게 되어 있어서
기존에 LogContainer에서 강의 프롬프트를 불러오던 방식을 변경해서 Review 컴포넌트에서 모두 불러온 후, LogContainer로 데이터를 넘겨주는 방식으로 개선했습니다.

Feature(#81,#86) 프로그래스바 음성 출력 구현

---

frontend/src/components/Header/components/HeaderProfileButton.tsx
frontend/src/components/Header/components/HeaderProfileModal.tsx
frontend/src/hooks/useAuth.ts
frontend/src/pages/Home/components/NewLectureBack.tsx
frontend/src/pages/UserAuth/components/UserAuthSection.tsx

- close #254 
로그인 시에 수정된 API를 통해 `token`과 함께 전달받는 `email`과 `username`을 local storage에 저장하도록 하였습니다.
home 페이지의 경우, guest도 접근이 가능해야 했기 때문에 이를 위해 header에서 accessToken과 username, email이 local storage에 존재하는지의 여부에 따라 다르게 보이도록 하였습니다.
강의 생성 버튼을 클릭했을 때, token이 존재하는지, 유효한지를 판단합니다. 유효하다면 username과 email이 존재하는지를 판단하여 없다면 이를 요청하여 local storage에 저장합니다. 반대로 accessToken이 유효하지 않다면 로그인 페이지로 이동하도록 하였습니다.
이를 `useAuth` 커스텀 훅을 작성하여 활용하였습니다.
```ts
import { useCallback } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { useToast } from "@/components/Toast/useToast";
const useAuth = () => {
const navigate = useNavigate();
const showToast = useToast();
const checkAuth = useCallback(() => {
const accessToken = localStorage.getItem("token");
if (!accessToken) { …
```

Fix(#254): home 페이지 강의 생성/조회 API 수정

---

mediaServer/src/RelayServer.ts
mediaServer/src/services/client.service.ts

여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요

FIX: 새로 방을 개설했을 때만, 강의 시작시간과 화이트보드 초기 데이터 반영

---

frontend/src/components/Header/Header.tsx
frontend/src/components/Header/components/HeaderInstructorControls.tsx
frontend/src/components/Header/components/HeaderLogo.tsx
frontend/src/components/Header/components/HeaderParticipantControls.tsx
frontend/src/utils/fabricCanvasUtil.ts
mediaServer/src/services/client.service.ts

Fix(#215) 발표자가 강의를 나갔다가 들어오는 경우 (새로고침 등) 강의를 계속 할 수 있게 한다.

---

frontend/src/components/Header/components/HeaderInstructorControls.tsx
frontend/src/components/Header/components/HeaderParticipantControls.tsx

진상님 디버깅을 위해 임시 추가합니다.
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요

hotfix: 참여자 페이지 게스트 토큰 임시 추가

---

mediaServer/src/RelayServer.ts

close #271 발표자에게 질문 해결 응답을 받으면, 해당 질문을 완료 처리한다.
redis streams의 consumer group을 사용해서, 질문이 해결되면 pending list에 존재하는 해당 질문을 ACK 요청해서, 추후 발표자 재 접속 시 해결된 질문을 제외하고 재전송 할 수 있도록 설정한다.
[#253](https://github.com/boostcampwm2023/web13_Boarlog/pull/253) PR에서 구현했던 updateQuestionStatus() 함수를 사용하여 진행했습니다. 
```
/** 
* event: solved
*/
{
"type": "question",
"roomId": ${roomId},
"questionId": ${questionId}
}
```
발표자가 질문 해결하면, 클라이언트에게 위와 같은 형태로 메시지를 받도록 구성했습니다.

Feat(#271): 질문 id와 solved 요청을 받으면, 해당 질문에 ACK 요청을 보낸다.

---

backend/src/lecture/lecture.controller.ts
backend/src/lecture/lecture.service.ts
mediaServer/src/RelayServer.ts
mediaServer/src/utils/MediaConverter.ts

여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요

Refactor: 미디어서버 HTTP Request 수정 및 백엔드 API 수정

---

mediaServer/src/models/FfmpegCommand.ts
mediaServer/src/utils/MediaConverter.ts
mediaServer/src/utils/ncp-storage.ts

Fix: NCP Object Storage에 mp3 파일 업로드 안되는 부분 수정

---

frontend/src/pages/Review/components/ProgressBar.tsx

프로그래스 바 마우스 다운 이벤트 발생 시 사라지는 버그 해결
원인: 드래그 기능 구현 초기에 프로그래스 바의 너비 조절이 딜레이가 생겨 그 문제를 해결하는 과정에서 남아있던 레거시 코드에 의해 버그가 발생했습니다.

Fix: 프로그래스 바 마우스 다운 이벤트 발생 시 사라지는 버그 해결

---

frontend/src/components/Header/components/HeaderInstructorControls.tsx
frontend/src/components/Header/components/HeaderParticipantControls.tsx

Fix: 토큰 만료된 사용자가 참여자 페이지에서 화이트보드를 볼 수 없는 문제 해결

---

frontend/src/components/Header/Header.tsx
frontend/src/pages/Review/Review.tsx

서버에서 받아온 데이터로 다시보기를 확인 할 수 있습니다.
다시보기 데이터를 서버에서 받아서 실행 할 수 있습니다.
https://github.com/boostcampwm2023/web13_Boarlog/assets/86391351/16f5895f-32fb-41aa-90b1-d42af5c77efa

Feature: 다시보기 완성

---

mediaServer/src/RelayServer.ts
mediaServer/src/listeners/lecture.listener.ts
mediaServer/src/models/RoomConnectionInfo.ts

미디어 서버 메모리 누수 close #302 
클라이언트가 새로고침 등으로 disconnect 됐을 경우, 이전 WebRTC 연결이 해제되지 않는 문제를 확인했습니다. 
클라이언트 disconnect시 WebRTC connection을 close 하도록 진행했습니다.

Fix: disconnect된 클라이언트의 WebRTC connection이 해제되지 않는 문제 해결

---

frontend/src/components/Header/components/HeaderInstructorControls.tsx
frontend/src/utils/fabricCanvasUtil.ts
mediaServer/src/constants/client-status.constant.ts
mediaServer/src/dto/room-info-request.dto.ts
mediaServer/src/dto/room-info-response.dto.ts
mediaServer/src/dto/server-answer.dto.ts
mediaServer/src/listeners/client.listener.ts
mediaServer/src/listeners/lecture.listener.ts
mediaServer/src/main.ts
mediaServer/src/models/ClientConnectionInfo.ts
mediaServer/src/repositories/room.repository.ts
mediaServer/src/services/lecture.service.ts
mediaServer/src/services/presenter.service.ts
mediaServer/src/services/socket.service.ts
mediaServer/src/services/webrtc-connection.service.ts
mediaServer/src/validation/client.validation.ts
mediaServer/src/validation/lecture.validation.ts

- #321 
화이트보드 화면 데이터를 담고 있는 ICanvasData의 objects 필드가 string에서 Uint8Array 타입으로 스펙이 변경되면서, Redis에서 현재 화이트보드 데이터를 가져올 때 타입이 맞지 않아 이슈가 발생했습니다.
- #314 
클라이언트에서 WebRTC 연결에 필요한 SDP와 Buffer 타입 데이터를 같이 보낼 때, 미디어 서버에서 SDP를 받아올 수 없는 이슈입니다.
1. Redis에서 가져온 현재 화이트보드 데이터가 JSON 문자열로 직렬화되어 있기 때문에, 역직렬화 후 화이트보드 화면 데이터만 Buffer 타입으로 변환해 주고 클라이언트에게 전달하여 해결했습니다.
2. 클라이언트에서 SDP와 Buffer 타입 데이터(화이트보드 화면 데이터)를 각각 보내도록 구성했습니다. 만약 발표자가 재접속한다면 화이트보드 화면이 초기화가 될 수 있기 때문에, 클라이언트별 상태 정보를 저장하여 재접속한 발표자인 경우에는 화이트보드 화면을 초기화 시키지 않도록 했습니다.

Fix(#314, #321): 화이트보드 편집이 반영되지 않는 이슈

---

backend/src/lecture/dto/response/response-lecture-record.dto.ts
backend/src/lecture/dto/whiteboard-event.dto.ts
backend/src/lecture/lecture.controller.ts
backend/src/lecture/lecture.module.ts
backend/src/lecture/lecture.service.ts
backend/src/lecture/schema/lecture-subtitle.schema.ts
backend/src/lecture/schema/whiteboard-log.schema.ts

close #320 Fix: Mongoose Schema property 타입 Uint8Array로 설정 시 에러
```Javascript
@Schema()
export class WhiteboardLog {
@Prop({ required: true })
objects: number[];
```
WhiteboardLog 스키마에서 objects 속성을 `Uint8Array`에서 `number[]` 속성으로 바꿨습니다.
<br>
```Javascript
export class WhiteboardEventDto {
objects: Uint8Array;
viewport: number[];
eventTime: number;
width: number;
height: number;
constructor(log?: WhiteboardLog) {
if (log) {
this.objects = new Uint8Array(log.objects);
this.viewport = log.viewport;
this.eventTime = log.eventTime;
this.width = log.width;
this.height = log.height;
}
}
}
```
`WhiteboardEventDto`에서는 DB에서 조회한 `WhiteboardLog`의 objects를 다시 Uint8Array 타입으로 캐스팅하여, 프론트엔드에서 받을 때 원래대로 타입 변화 없이 받을 수 있도록 합니다. 생성자 오버로딩으로 Controller에서 Body로 받을 때와 응답할 때 모두 사용할 수 있도록 했습니다.
<br>
```Javascript …
```

Fix(#320): Mongoose Schema 속성 타입 Uint8Array 지원 안 하는 문제 해결
