- .github/workflows/github_actions_cd.yml
- .github/workflows/github_actions_ci.yml
- backend/.dockerignore
- backend/Dockerfile
> Feature(#5): backend CI/CD 파이프라인 구축

- backend/Dockerfile
#5 Backend CI/CD 파이프라인 구축 시 도커 이미지가 정상적으로 빌드되지 않는 문제 해결
> Fix(#5): 도커 이미지 빌드 에러 해결

- frontend/src/App.tsx
- frontend/src/global.css
- frontend/src/pages/Login/Login.tsx
- frontend/src/pages/Login/components/Header.tsx
- frontend/src/pages/Login/components/LoginSection.tsx
Feature: 버튼을 클릭하여 구글 소셜 로그인을 진행할 수 있다. #7 
login 페이지에 필요한 header와 loginSection component의 프로토타입을 개발한 후, 이를 활용하여 login 페이지의 UI를 구성하였습니다.
> Feature(#7): login 페이지 UI 프로토타입 구현

- frontend/package-lock.json
- package-lock.json update
cloudflare 배포 오류를 해결하기 위해 package-lock.json을
업데이트하였습니다.
> Fix: package-lock.json 업데이트

- frontend/src/pages/Test/components/CanvasSection.tsx
#110 
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
> Fix(#110) Test 페이지 TypeScript 오류 해결

- backend/.gitignore
- backend/package-lock.json
- backend/package.json
- backend/src/app.module.ts
- backend/src/auth/auth.controller.ts
- backend/src/auth/auth.module.ts
- backend/src/auth/auth.service.ts
- backend/src/auth/dto/userInfo.dto.ts
- backend/src/auth/google.strategy.ts
- backend/src/schema/user.schema.ts
#8 #114
배포 서버에 DB를 설정해두긴 했는데 해당 DB에 개발할 때 테스트용으로 사용하면 안 된다고 판단했습니다. 현재는 로컬에 있는 MongoDB를 사용하여 개발하고 있습니다.
> Feature(#8 #114): 회원가입 및 구글 로그인

- mediaServer/src/RelayServer.ts
- mediaServer/test/presenter/index.html
> Fix: 미디어 서버에서 클라이언트 MediaStream 정상적으로 받지 못하는 문제 해결

- frontend/src/components/Header/components/HeaderInstructorControls.tsx
- frontend/src/components/Header/components/HeaderSettingModal.tsx
- frontend/src/components/Header/components/stateMicVolme.tsx
- frontend/src/pages/MicTest/components/AudioRecord.tsx
- mediaServer/src/RelayServer.ts
#67
설정 모달에서 발표자 마이크 음량을 조절할 수 있습니다.
조절된 오디오 트랙을 새로운 미디어 스트림으로 만들어서 서버에 보내주도록 했습니다.
실제로 서버에 잘 전송되는지는 나중에 미디어 서버 완성되면 테스트 해보겠습니다.
다 작성하려면 오래 걸릴 것 같아서 금~주말 이용해서 작성하겠습니다.
https://github.com/boostcampwm2023/web13_Boarlog/assets/86391351/0ff3e4ce-fff8-4336-9ea7-9ba8f36656cb
> Feature(#67) 설정 모달에서 발표자 마이크 음량을 설정할 수 있다.

- backend/.prettierrc
- backend/src/app.module.ts
- backend/src/room/dto/create-room.dto.ts
- backend/src/room/room.controller.ts
- backend/src/room/room.module.ts
- backend/src/room/room.schema.ts
- backend/src/room/room.service.ts
- backend/src/utils/GenerateUtils.ts
강의실을 생성하는 API를 구현했습니다. close #27 
강의 제목 · 내용과 함께 강의 생성 요청을 받으면 해당 내용을 DB에 저장하고, 유니크한 강의 참여 코드를 생성하여 반환하도록 구현했습니다.
> Feature(#27) 강의실 생성 API 구현

- mediaServer/src/RelayServer.ts
- mediaServer/src/main.ts
- mediaServer/test/presenter/index.html
- mediaServer/test/student/index.html
미디어서버에서 발표자 MediaStream 참여자에게 전달 close #133 
발표자가 접속할 때 발표자의 MediaStream을 서버에서 가지고 있는다. 이후 참여자가 접속할 때마다 미디어서버와 참여자 사이 connection을 만드는 과정에서 발표자의 MediaStreamTrack을 전달한다. 이렇게 되면 참여자는 본인의 MediaStream이 아닌 발표자의 MediaStream을 받을 수 있게 된다.
> Feature(#133) 미디어서버에서 발표자 MediaStream을 참여자에게 전달한다.

- backend/src/app.module.ts
- backend/src/auth/dto/userInfo.dto.ts
- backend/src/lecture/lecture.module.ts
- backend/src/lecture/lecture.schema.ts
- backend/src/main.ts
- backend/src/schema/user.schema.ts
- backend/src/user/dto/username.update.dto.ts
- backend/src/user/user.controller.ts
- backend/src/user/user.module.ts
- backend/src/user/user.service.ts
마이페이지 API 구현 close #136
마이페이지에서 프로필 정보와 수강한 강의 목록을 확인하고, 닉네임을 수정하는 기능이 필요합니다.
따라서 필요한 정보를 응답하고, 닉네임 수정 로직을 추가했습니다.
논의 할 부분이 있어서, 논의 후 변경사항이 있다면 추가로 커밋하고 내용 추가 예정입니다.
> Feature(#136): 마이페이지 API 구현

- backend/src/room/dto/create-room.dto.ts
- backend/src/room/dto/enter-room.dto.ts
- backend/src/room/room-code.schema.ts
- backend/src/room/room.controller.ts
- backend/src/room/room.module.ts
- backend/src/room/room.service.ts
- backend/src/user/dto/user.update.dto.ts
- backend/src/user/user.controller.ts
- backend/src/user/user.service.ts
사용 중인 입장 코드 반환을 방지하기 위해, 입장 코드를 DB에서 관리하고, 강의실 입장 시 해당 유저의 수강한 강의 목록에 추가한다. close #139
> Feature: DB에서 참여 코드 관리 & 강의실 입장 시 해당 유저의 수강한 강의 목록에 추가 

- frontend/src/components/Header/components/HeaderInstructorControls.tsx
close #138 서버 연결 후 마이크 입력 장치 변경이 반영되지 않는 오류를 해결하기 위한 PR입니다.
주말에는 푹 쉬시고 월요일에 확인 후 간단하게 리뷰 부탁드립니다.
마이크의 오디오가 미디어스트림에 연결되는 과정이 서버에 처음 연결될 때("강의 시작"버튼 눌렀을 때)만 일어났기 때문에 일어난 문제였습니다.
강의 시작 이후 오디오를 변경하면 이미 서버에 연결된 미디어스트림이 있어서 아래와 같은 방법으로 해결했습니다.
1. 마이크가 변경되었을 때 useEffect로 감지후, replaceAudioTrack() 함수를 실행시킵니다.
2. replaceAudioTrack() 함수에서는 기존 미디어트랙을 중지 후, 새 미디어 트랙을 만들어 setupAudioAnalysis()함수에 전달합니다.
3. setupAudioAnalysis()함수는 새 미디어 트랙을 가지고 분석과 변조를 시작하고, 새 미디어스트림을 만들어 updatedStreamRef.current에 저장합니다.
4. 다시 replaceAudioTrack() 함수로 돌아와서, 현재 연결된 RTCPeerConnection의 오디오 트랙을 새 오디오 트랙으로 변경해주는 식으로 해결 했습니다.
여기에 작성하세요
https://github.com/boostcampwm2023/web13_Boarlog/assets/86391351/0756c1ce-fbf6-47b8-bda8-3f993356e81e
#135번 PR의 미디어서버와 참여자 페이지 조금 수정해서 테스트 해본 결과입니다.
볼륨바를 이용해서 바뀐 마이크의 음성이 잘 반영되는 것 확인했습니다.
> Fix(#138) 서버 연결 후 마이크 입력 장치 변경 반영되도록 수정

- frontend/package-lock.json
- frontend/src/pages/Test/components/StickyNoteEditPanel.tsx
- frontend/src/pages/Test/components/Toolbar.tsx
- frontend/src/pages/Test/components/getStickyNoteInstance.ts
- frontend/src/pages/Test/components/stateStickyNoteInstance.ts
메모의 텍스트를 수정 기능 구현 close #48 
- 사각형, 텍스트박스 두 객체를 그룹해 생기는 문제로 이를 해결하기 위한 방법을 서치해보니 두 개 정도의 아이디어가 있었습니다.
1. 메모지 그룹 해제 → 텍스트 박스 수정 → 메모지 그룹화
2. 기존 텍스트 박스 숨기기 → 메모지의 기존 텍스트 박스 요소 복제 → 복제된 새 텍스트박스 요소에 텍스트를 입력 → 입력 완료 후 기존 텍스트에 내용 반영 → 복제된 새 택스트박스 제거 → 기존 텍스트 박스 표시
- 1번 아이디어의 장, 단점
- 장점: 로직이 단순해 구현이 용이하다.
- 단점: 그룹을 해제하는 과정에서 인스턴스가 제거 후 재생성되기 때문에 다른 곳에서 메모 인스턴스가 참조되고 있다면 이를 다시 연결해줘야하는 문제가 있다. 이벤트도 다시 재등록 해줘야한다.
- 2번 아이디어의 장, 단점
- 장점: 그룹 인스턴스를 재생성 할 필요가 없다. 이벤트를 재등록 할 필요가 없다.
- 단점: 수정하는 과정이 너무 복잡하다.
- 2번 아이디어를 선택해서 구현하기로 결정했습니다. 그룹 인스턴스를 재생성 할 필요가 없다. 이벤트를 재등록 할 필요가 없다라는 장점 덕에 후에 다른 분들이 관련 기능을 구현하더라도 그룹 인스턴스에 대한 참조를 다시 갱신해야할 가능성을 미연에 방지할 수 있다고 생각했기 때문입니다.
https://github.com/boostcampwm2023/web13_Boarlog/assets/54176384/46cb9be9-d09b-4cb6-9e6d-8e95bab3efda
> Feature(#48):  메모의 텍스트를 수정 기능 구현

- mediaServer/package-lock.json
- mediaServer/package.json
- mediaServer/src/RelayServer.ts
- mediaServer/src/RoomInfo.ts
- mediaServer/src/main.ts
- mediaServer/src/models/ClientInfo.ts
- mediaServer/src/models/Message.ts
- mediaServer/src/models/RoomInfo.ts
- mediaServer/src/pc.config.ts
- mediaServer/test/presenter/index.html
- mediaServer/test/student/index.html
미디어 서버에서 여러 강의실을 관리할 수 있도록 구성한다 close #146
발표자의 화이트보드 수정사항을 강의실 참여자에게 브로드캐스팅한다. close #45
강의실에 있는 참여자의 질문을 발표자에게 전달한다. close #87
중간에 강의실에서 나갈 시, 강의실 정보에서 해당 참여자를 제거한다. close #156
강의 종료 시 해당 강의실 정보와 발표자와 참여자의 소켓 정보를 제거한다. close #30
한 큐에 구현할 수 있는 것들이라 하나의 PR에 담았습니다.
잘 동작하는지 확인 후 리팩토링 진행하겠습니다.
> Feature(#30, #45, #87, #146, #156): 미디어 서버에서 여러 강의실을 관리하고, 화이트보드 & 질문 & 강의 종료 & 강의 나가기를 지원한다

- frontend/src/pages/Test/components/Toolbar.tsx
- frontend/src/pages/Test/components/getStickyNoteInstance.ts
글자가 개행됨에 따라 메모지 크기 조절 기능 구현
https://github.com/boostcampwm2023/web13_Boarlog/assets/54176384/64b472a9-9d00-4a60-a94b-0a125e521d35
> Feature: 글자가 개행됨에 따라 메모지 크기 조절 기능 구현 #172

- frontend/src/components/Header/components/HeaderInstructorControls.tsx
- frontend/src/components/Header/components/HeaderParticipantControls.tsx
close #65 `강의자가 강의 시작/종료 버튼을 클릭하여 시작, 종료를 할 수 있다. 알림창을 표시하여 다시 확인한다.`
https://github.com/boostcampwm2023/web13_Boarlog/assets/86391351/1c5967a0-0303-4732-97e0-2db60afe4405
> Feature(#65) 디버깅 버튼 제거, 강의 시작시 알림 모달을 띄워 다시 확인

- frontend/package-lock.json
- frontend/package.json
Axios 라이브러리 설치 close #188 
하단 문서를 참고하여 install을 진행하였습니다.
- [Axios 공식 github](https://github.com/axios/axios)
> Feature(#188): Axios 라이브러리 설치

- mediaServer/src/RelayServer.ts
- mediaServer/src/models/RoomInfo.ts
참여자가 강의실 입장 시 강의 시작 시간을 전달한다. close #196
> Feature(#196): 참여자가 강의실 입장 시 강의 시작시간 전달

- frontend/src/components/Header/components/HeaderInstructorControls.tsx
- frontend/src/components/Header/components/HeaderParticipantControls.tsx
> Refactor: API 요청 관련 URL env 처리

- frontend/src/components/Header/components/HeaderInstructorControls.tsx
- frontend/src/components/Header/components/HeaderParticipantControls.tsx
오늘 데일리스크럼에서 나온 문제를 해결했습니다.
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
> fix: 소켓 연결을 일찍 닫아버리는 문제 및 참여자 페이지 소켓 연결 순서 변경

- frontend/src/pages/Review/Review.tsx
- frontend/src/pages/Review/components/ProgressBar.tsx
> refact: 컨플릭트 해결 과정에서 실수한 부분 해결

- mediaServer/src/RelayServer.ts
- mediaServer/src/dto/room-info.dto.ts
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
> Fix(#262): 발표자 연결 수립 과정에서 화이트보드 초기 데이터 받을 수 있도록 구성

- frontend/src/pages/Review/Review.tsx
- mediaServer/src/RelayServer.ts
close #215 `발표자가 강의를 나갔다가 들어오는 경우 (새로고침 등) 강의를 계속 할 수 있게 한다.`
강의자가 새로고침 후 다시 접속해도 음성이 참여자에게 잘 전달되도록 미디어 서버를 수정했습니다.
https://github.com/boostcampwm2023/web13_Boarlog/assets/86391351/b4d1f018-98fa-4bd5-840b-4c5ec352d4b4
> feature(#215) 강의자가 새로고침 후 재접속 해도 음성이 잘 들리도록 개선 

- frontend/src/components/Header/components/HeaderParticipantControls.tsx
- frontend/src/pages/Review/Review.tsx
- frontend/src/pages/Review/components/ProgressBar.tsx
로그인 되어있지 않은 게스트 참여자는 첫 소켓에서 빈값을, 두번째 소켓에서
첫 소켓의 socketid를 보내도록 변경했습니다.
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
> feature: 참여자가 socket id 전송하도록 개선

- mediaServer/src/RelayServer.ts
- mediaServer/src/models/FfmpegCommand.ts
- mediaServer/src/utils/MediaConverter.ts
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
> Feature: 미디어서버에서 API 서버로 요청 보내기

- frontend/src/pages/UserAuth/components/UserAuthSection.tsx
> Feature(#278): Enter keydown event 추가

- mediaServer/src/RelayServer.ts
- mediaServer/src/dto/asked.request.dto.ts
발표자에게 질문 전달 시 questionId가 정상적으로 전달이 안되는 부분 수정
DTO 형태로 만들어서 정상적으로 전달될 수 있도록 수정했습니다.
> Fix: 발표자에게 질문 전달 시 questionId가 정상적으로 전달이 안되는 부분 수정

- backend/src/lecture/dto/whiteboard-event.dto.ts
- backend/src/lecture/lecture.service.ts
- backend/src/lecture/schema/whiteboard-log.schema.ts
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
> Refactor: API requestDTO 형식 수정

- frontend/src/components/Header/components/HeaderInstructorControls.tsx
- frontend/src/pages/Test/components/CanvasSection.tsx
캔버스 관련 이슈 해결
- 강의자가 질문을 받고 나서 강의를 종료한 후, 새 강의를 실행할 때 이전 질문이 남아있습니다.
- 그래픽 요소가 backspace나 delete로 해결되지 않음
여기에 작성하세요
여기에 작성하세요
> Fix(#280): 캔버스 관련 이슈

- mediaServer/src/RelayServer.ts
- mediaServer/src/constants/client-type.constant.ts
- mediaServer/src/dto/serverAnswer.dto.ts
- mediaServer/src/services/participant.service.ts
close #244 클라이언트 타입에 GUEST 타입 추가
> Feature(#244): 참여자 GUEST 타입 추가

- mediaServer/src/RelayServer.ts
- mediaServer/src/models/FfmpegCommand.ts
- mediaServer/src/utils/MediaConverter.ts
> Fix: 게스트 참여자 정상적으로 적용안되는 부분 수정

- backend/src/user/user.service.ts
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
> Fix: 수강목록 종료된 강의만 불러오기

- mediaServer/src/utils/MediaConverter.ts
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
여기에 작성하세요
> Feat: CLOVA 장문 음성추출 API 호출

- backend/package-lock.json
- backend/package.json
- backend/src/lecture/lecture.controller.ts
- backend/src/lecture/lecture.module.ts
- backend/src/lecture/lecture.service.ts
- backend/src/user/user.controller.ts
- backend/src/user/user.module.ts
- backend/src/user/user.service.spec.ts
- backend/src/user/user.service.ts
close #318 Refactor: UserService 테스트코드 추가 
여기에 작성하세요
```Javascript
const module = await Test.createTestingModule({
providers: [UserService,
{
provide: getModelToken(User.name),
useValue: Model
}
]
}).compile();
service = module.get<UserService>(UserService);
model = module.get<Model<User>>(getModelToken(User.name));
```
테스트용 모듈을 다음과 같이 생성합니다.
<br>
```Javascript
describe('updateUsername', () => {
const id = new Types.ObjectId();
const email = "test@gmail.com";
const username = "testname";
it('should throw NotFoundException', async () => {
jest.spyOn(model, 'findOneAndUpdate').mockResolvedValue(null);
await expect(service.updateUsername(email, username)).rejects.toThrow(NotFoundException);
})
it('should update username', async () => {
jest.spyOn(model, …
```
> Refactor(#318): UserService 테스트코드 추가
